Bug #1:

Traversal to a user without authentication:
http://127.0.0.1:5000/user/{username}
User enumeration of a URL
Bruteforce of usernames of this address and an apprpriate response.  Any request that comes back with "ERROR:" in the response.text field is not a valid user.

See bug_1.py for exploit


Bug #2:
all users are valid using bug#1, there is no check for this --> further development of the backend database.  
Fixed --> check is made in the "username" field for if the user exists in the database